# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 246d69ee3a813e6d3a6bae92460ad62fcada34cc922f16f58b1cfd50d70246f809e613d932b75ccd65ee0a003637ce9019b1e4145b83ee82365e5c5c7edfc3bc

test:
  secret_key_base: 19cb6f56b6723d6f96119e4db2fd929c6fa586ca274ac55120741667edf075a953f13d612757d9cd34f1bd0c7bbe6f88c8bcb5f2da2954159342918764dde8cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
